"""add analysis cache table

Revision ID: 8eca761d869f
Revises: cb49d9a5e5f5
Create Date: 2026-03-24 15:22:16.764864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eca761d869f'
down_revision = 'cb49d9a5e5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fen', sa.String(length=100), nullable=False),
    sa.Column('evaluation', sa.Float(), nullable=True),
    sa.Column('best_move', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_cache_fen'), ['fen'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_cache_fen'))

    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
