"""add onboarding fields to users

Revision ID: a033f0b8d66e
Revises: 0c2728a187d5
Create Date: 2026-04-16 15:55:15.006046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a033f0b8d66e'
down_revision = '0c2728a187d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('placement_test_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('placement_game_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('placement_game_id')
        batch_op.drop_column('placement_test_score')
        batch_op.drop_column('onboarding_completed')

    # ### end Alembic commands ###
