"""add lesson content fields to daily_tasks

Revision ID: d7014212cbd2
Revises: a57947c5e4ed
Create Date: 2026-04-07 14:56:37.976239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7014212cbd2'
down_revision = 'a57947c5e4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_content', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('quiz_questions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('quiz_passed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quiz_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content_generated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.drop_column('content_generated')
        batch_op.drop_column('quiz_score')
        batch_op.drop_column('quiz_passed')
        batch_op.drop_column('quiz_questions')
        batch_op.drop_column('lesson_content')

    # ### end Alembic commands ###
